/*
Summary info: Program will ask the user how many tickets for each class of seats were sold.
The program will then output the number of tickets sold for each class and the amount of income 
generated by each class. The program will then output the total income generated by all the classes.
Programmer: Francioso, Joseph
Date due: 04OCT2016
Date finished: 04OCT2016
*/
import java.util.Scanner;
import java.text.NumberFormat;
import java.text.DecimalFormat;

public class TicketSales 
{
public static void main(String[] args)
{

//Create scanner to obtain scanner input
Scanner scanner1 = new Scanner(System.in);

//initialize a new variable to format doubles to two decminal places so that the decimal doesn't run on forever
NumberFormat formatter = new DecimalFormat("#0.00"); 

//obtain user input
System.out.println("How many tickets were sold for Class A seats?: ");
int aTickets = scanner1.nextInt();
//multiply number of tickets by ticket amount for Class A tickets
double aTicketsAmount = aTickets * 22.99;
System.out.println("$"+ formatter.format(aTicketsAmount) + " was earned through the sales of " + aTickets + "A tickets");

System.out.println("How many tickets were sold for Class B seats?: ");
int bTickets = scanner1.nextInt();
double bTicketsAmount = bTickets * 14.99;
System.out.println("$"+ formatter.format(bTicketsAmount) + " was earned through the sales of " + bTickets + "B tickets");

System.out.println("How many tickets were sold for Class C seats?: ");
int cTickets = scanner1.nextInt();
double cTicketsAmount = cTickets * 9.99;
System.out.println("$"+ formatter.format(cTicketsAmount) + " was earned through the sales of " + cTickets + "C tickets");

double totalRevenue = aTicketsAmount + bTicketsAmount + cTicketsAmount;
System.out.println("$"+ formatter.format(totalRevenue) + " was earned through the sales of A, B, and C tickets.");
    }
}